dataset: flowers # [flowers, penguins]
network_type: diamond # [diamond, short]
epochs: 500 # any positive integer
test_size: 0.2 # any float between 0 and 1 non-inclusive 
seed: 42 # any integer 
n_testseeds: 10 # any positive integer
kfold_k: 10 #  any positive integer 
lr: 0.005 # any positive real number 
batch_size: -1 # [-1] U any positive integer
max_recorded_samples: 56 # any positive integer 
n_alphas: 5 # any positive integer
features: all # [all] U dataset columns
labels: species # dataset columns

activations: # [Tanh, IPLo, ReLU] - add more in config.py
  - Tanh
  - IPLo
  - ReLU

eval_metrics: # see list of all allowed metrics in config.py
  - precision
  - recall
  - f1
  - mcc

reducers: # see list of all allowed reducers in config.py
  - log_average
  - mean
  - stdeviation
  - norm

kf_reducers: # in config.py
  - mean
  - stdeviation

categories: # [grad, testloss, testpreds, metrics, agrad, aouts, ls] - add more in categories folder
  - grad
  - testloss
  - testpreds
  - metrics
  - agrad
  - aouts
  - ls

activation_mods: # LS only as activation mods
  Tanh:
     LS:
      alpha: 0.25
      learnable: true
  IPLo:
    LS:
      alpha: 0.20
      learnable: false

network_mods: # [batchnorm, layernorm, dropout, residual]
  diamond:
    batchnorm: true
    dropout:
      p: 0.20
    residual:
      block_size: 3
  
  short:
    layernorm: true