epochs: 500
test_size: 0.2
seed: 42
lr: 0.005
max_samples: 51
kfold_k: 10
features: [bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g]
labels: [sex]
activations: [ReLU, IPLo, Tanh]
eval_metrics: [accuracy]
reducers: [log_average, mean, variance]
kf_reducers: [mean, variance]
categories: [testloss]